FROM node:12

COPY package*.json ./

RUN npm install

ARG DB_DATABASE
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT

ARG JWT_SECRET
ARG JWT_EXPIRATION

ARG GOOGLE_CLIENT_ID
ARG GOOGLE_SECRET

ARG DOMAIN

ARG MAILGUN_API_KEY
ARG MAILGUN_DOMAIN

ENV DB_DATABASE=$DB_DATABASE
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT

ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRATION=$JWT_EXPIRATION

ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_SECRET=$GOOGLE_SECRET

ENV DOMAIN=$DOMAIN

COPY . .

CMD npm run start